In [21]:
import numpy as np
import pandas as pd

In [2]:
num=np.array([1,2,3])

In [3]:
num

array([1, 2, 3])

# How to create an empty and a full NumPy array?

In [12]:
np.empty((3,3))

array([[4.67296746e-307, 1.69121096e-306, 1.33511290e-306],
       [6.23058368e-307, 2.22526399e-307, 6.23053614e-307],
       [7.56592338e-307, 9.34588061e-307, 3.62651150e-317]])

In [16]:
a=np.full((3,5),55)

In [18]:
a[0][0]

55

# Create a Numpy array filled with all zeros | Python

In [23]:
a=np.zeros((3,5))
b=pd.DataFrame(a)
b

0    1    2    3    4
0  0.0  0.0  0.0  0.0  0.0
1  0.0  0.0  0.0  0.0  0.0
2  0.0  0.0  0.0  0.0  0.0

# Create a Numpy array filled with all ones

In [25]:
a=np.ones((3,6))
b=pd.DataFrame(a)
b

0    1    2    3    4    5
0  1.0  1.0  1.0  1.0  1.0  1.0
1  1.0  1.0  1.0  1.0  1.0  1.0
2  1.0  1.0  1.0  1.0  1.0  1.0

# Check whether a Numpy array contains a specified row

In [26]:
Arr = [[1,2,3,4,5], [6,7,8,9,10], [11,12,13,14,15], [16,17,18,19,20]]

In [34]:
a=np.array(Arr)
a

array([[ 1,  2,  3,  4,  5],
       [ 6,  7,  8,  9, 10],
       [11, 12, 13, 14, 15],
       [16, 17, 18, 19, 20]])

In [35]:
print([1,2,3,4,5] in a.tolist())
print([1,2,3,-8,5] in a.tolist())
print([1,-2,3,4,5] in a.tolist())
print([1,2,3,4,-5] in a.tolist())

True
False
False
False


# How to Remove rows in Numpy array that contains non-numeric values?

In [46]:
a=np.array([[1,5,7],
          [1,np.nan,np.nan]])

In [47]:
print(a[~np.isnan(a).any(axis=1)])

[[1. 5. 7.]]


In [43]:
# Importing Numpy module
import numpy as np

# Creating 2X3 2-D Numpy array
n_arr = np.array([[10.5, 22.5, 3.8],
				[41, np.nan, np.nan]])

print("Given array:")
print(n_arr)

print("\nRemove all rows containing non-numeric elements")
print(n_arr[~np.isnan(n_arr).any(axis=1)])


Given array:
[[10.5 22.5  3.8]
 [41.   nan  nan]]

Remove all rows containing non-numeric elements
[[10.5 22.5  3.8]]


In [53]:
in_arr = np.array([[[2, 2, 2], [2, 2, 2]]])
in_arr.shape

(2, 1, 2, 3)

In [57]:
import numpy as np

arr = np.array([[1, 2, 3], [4, 5, 6]])
aw=pd.DataFrame(arr)
aw

0  1  2
0  1  2  3
1  4  5  6

In [ ]:
# the shape of a one-dimensional array is (n,), 
# the shape of a two-dimensional array is (n, m), and the shape of a three-dimensional array is (n, m, k).

In [68]:
n_ip=np.arange(9).reshape(1,3,3)
print(n_ip.shape)
print(n_ip.ndim)

(1, 3, 3)
3


In [69]:
n_op=np.squeeze(n_ip,axis=0)
print(n_op.shape)
print(n_op.ndim)

(3, 3)
2


# Find the number of occurrences of a sequence in a NumPy array

In [70]:
Arr = [[2,8,9,4],
       [9,4,9,4],
       [4,5,9,7],
       [2,9,4,3]]
ar=np.array(Arr)
seq = [9,4] 



In [78]:
out=repr(ar).count("9, 4")

print(out)

4


In [77]:
# importing package
import numpy

# create numpy array
arr = numpy.array([[2, 8, 9, 4],
				[9, 4, 9, 4],
				[4, 5, 9, 7],
				[2, 9, 4, 3]])

# Counting sequence
output = repr(arr).count("9, 4")

# view output
print(output)


4


In [83]:
x = np.array([1, 1, 1, 2, 3, 4, 2, 4, 3, 3,2 ])
print("Original array:")
print(x)

Original array:
[1 1 1 2 3 4 2 4 3 3 2]


In [84]:
y=np.bincount(x)
maximum=max(y)
maximum

3

In [91]:
for i in range(len(y)):
    if y[i]==maximum:
        print(y,end=' ')

[3 3 3 3 3] [3 3 3 3 3] [3 3 3 3 3] [3 3 3 3 3] [3 3 3 3 3] 

In [94]:
a=np.arange(5)
b=np.arange(10).reshape(2,5)

for i,y in np.nditer([a,b]):
    print((i,y))

(array(0), array(0))
(array(1), array(1))
(array(2), array(2))
(array(3), array(3))
(array(4), array(4))
(array(0), array(5))
(array(1), array(6))
(array(2), array(7))
(array(3), array(8))
(array(4), array(9))


In [99]:
a=np.arange(3)
b=np.arange(3)

c=np.array(np.meshgrid(a,b)).T.reshape(-1,2)
c

array([[0, 0],
       [0, 1],
       [0, 2],
       [1, 0],
       [1, 1],
       [1, 2],
       [2, 0],
       [2, 1],
       [2, 2]])

In [ ]:
# How to add a border around a NumPy array?

In [100]:
a=np.array([[1,2],[5,4]])

In [102]:
b=np.pad(a,pad_width=2,mode='constant',constant_values=0)
b.ndim

2

In [ ]:
# comparison of two arrays

In [103]:
an_array = np.array([[1, 2], [3, 4]])
other_array = np.array([[1, 2], [3, 4]])

comp=an_array==other_array

print(comp)

[[ True  True]
 [ True  True]]


In [104]:
an_array = np.array([[1, 2], [3, 4]])
other_array = np.array([[1, 2], [3, 4]])

comp=an_array==other_array
comp1=comp.all()

print(comp1)

True


In [ ]:
# How to check whether specified values are present in NumPy array?

In [105]:
an_array = np.array([[1, 2], [3, 4]])

print(2 in an_array)
print(4 in an_array)
print(-1 in an_array)
print(22 in an_array)

True
True
False
False


# How to get all 2D diagonals of a 3D NumPy array?

In [106]:
arr = np.arange(3 * 4 * 4).reshape(3, 4, 4)
arr

array([[[ 0,  1,  2,  3],
        [ 4,  5,  6,  7],
        [ 8,  9, 10, 11],
        [12, 13, 14, 15]],

       [[16, 17, 18, 19],
        [20, 21, 22, 23],
        [24, 25, 26, 27],
        [28, 29, 30, 31]],

       [[32, 33, 34, 35],
        [36, 37, 38, 39],
        [40, 41, 42, 43],
        [44, 45, 46, 47]]])

In [110]:
arr1=np.diagonal(arr)
arr1.ndim

2

# Flatten a Matrix in Python using NumPy

In [114]:
arr1.flatten()

array([ 0, 20, 40,  1, 21, 41,  2, 22, 42,  3, 23, 43])

In [113]:
b=arr1.flatten()
b.shape

(12,)

In [112]:
list(arr1.flatten())

[0, 20, 40, 1, 21, 41, 2, 22, 42, 3, 23, 43]

# Python | Flatten a 2d numpy array into 1d array

In [116]:
a=np.array([[1,2],[5,4]])
print(a.shape)

b=a.flatten()

print(b.shape)

(2, 2)
(4,)


In [118]:
arr = np.zeros((1, 2, 3, 4))
  
gfg = np.moveaxis(arr, 0, -1).shape
  
print (gfg)

(2, 3, 4, 1)


In [119]:
gfg = np.moveaxis(arr, 0, -1)
gfg

array([[[[0.],
         [0.],
         [0.],
         [0.]],

        [[0.],
         [0.],
         [0.],
         [0.]],

        [[0.],
         [0.],
         [0.],
         [0.]]],


       [[[0.],
         [0.],
         [0.],
         [0.]],

        [[0.],
         [0.],
         [0.],
         [0.]],

        [[0.],
         [0.],
         [0.],
         [0.]]]])

In [123]:
arr = np.zeros((1, 2, 3, 4))
arr

array([[[[0., 0., 0., 0.],
         [0., 0., 0., 0.],
         [0., 0., 0., 0.]],

        [[0., 0., 0., 0.],
         [0., 0., 0., 0.],
         [0., 0., 0., 0.]]]])

In [124]:
numpy.count_nonzero(arr) 

0

In [125]:
# Python program explaining
# numpy.count_nonzero() function

# importing numpy as geek
import numpy as geek

arr = [[0, 1, 2, 3, 0], [0, 5, 6, 0, 7]]

gfg = np.count_nonzero(arr)

print (gfg)


6


In [126]:
# Python program explaining
# numpy.count_nonzero() function

# importing numpy as geek
import numpy as geek

arr = [[0, 1, 2, 3, 0], [0, 5, 6, 0, 7]]

gfg = geek.count_nonzero(arr)

print (gfg)


6


In [127]:
# Python program explaining
# numpy.size() method

# importing numpy
import numpy as np

# Making a random array
arr = np.array([[1, 2, 3, 4], [5, 6, 7, 8]])

# By default, give the total number of elements.
print(np.size(arr))


8


In [ ]:
# numpy.trim_zeros() in Python

In [128]:
import numpy as geek

gfg = np.array((0, 0, 0, 0, 1, 5, 7, 0, 6, 2, 9, 0, 10, 0, 0))

# without trim parameter
# returns an array without leading and trailing zeros

res = np.trim_zeros(gfg)
print(res)


[ 1  5  7  0  6  2  9  0 10]


In [130]:
import numpy as np
          
# make matrix with numpy
gfg = np.matrix('[64, 1; 12, 3]')

gfg.max()

64

In [133]:
import numpy as np
          
# make matrix with numpy
gfg = np.matrix([[12,3],[2,5]])
gfg.min()

2

# Find the number of rows and columns of a given matrix using NumPy

In [137]:
gfg = np.matrix('[64, 1; 12, 3]')

gfg.shape

(2, 2)

In [138]:
# import the important module in python
import numpy as np
			
# make matrix with numpy
gfg = np.matrix('[4, 1, 12, 3, 4, 6, 7]')
			
# applying matrix.take() method
geek = gfg.take(2)
	
print(geek)


[[12]]


In [142]:
gfg[0,2]

12

In [ ]:
# Python | Numpy matrix.sum()

In [143]:
# import the important module in python
import numpy as np
			
# make matrix with numpy
gfg = np.matrix('[4, 1, 12, 3, 4, 6, 7]')
			
# applying matrix.take() method
geek = gfg.sum()
	
print(geek)


37


In [144]:
# importing Numpy package
import numpy as np

# creating a 3X3 Numpy matrix
n_array = np.array([[55, 25, 15],
					[30, 44, 2],
					[11, 45, 77]])

# Displaying the Matrix
print("Numpy Matrix is:")
print(n_array)

# calculating the Trace of a matrix
trace = np.trace(n_array)


print("\nTrace of given 3X3 matrix:")
print(trace)


Numpy Matrix is:
[[55 25 15]
 [30 44  2]
 [11 45 77]]

Trace of given 3X3 matrix:
176


In [146]:
# creating a 3X3 Numpy matrix
n_array = np.array([[55, 25, 15],
					[30, 44, 2],
					[11, 45, 77]])

res=np.trace(n_array)

res

176

# Calculate the sum of the diagonal elements of a NumPy array

In [152]:
#Suppose we have two matrices A and B.
A = [[1,2],[3,4]]
B = [[4,5],[6,7]]

res=np.add(A,B)
print('Addin the two matrices\n',res)
res1=np.multiply(A,B)
print('mul the two matrices\n',res1)

Addin the two matrices
 [[ 5  7]
 [ 9 11]]
mul the two matrices
 [[ 4 10]
 [18 28]]


In [156]:
ini_array = np.array([[1, 2, 3], [45, 4, 7], [9, 6, 10]])

col=np.array([[1],[2],[3]])

res=np.append(ini_array,col,axis=1)
res

array([[ 1,  2,  3,  1],
       [45,  4,  7,  2],
       [ 9,  6, 10,  3]])

In [159]:
ini_array = np.array([[1, 2, 3], [45, 4, 7], [9, 6, 10]])

col=np.array([[1],[2],[3]])

res=np.concatenate((ini_array,col),axis=1)
res

array([[ 1,  2,  3,  1],
       [45,  4,  7,  2],
       [ 9,  6, 10,  3]])

In [160]:
p = [[1, 2], [2, 3]]
q = [[4, 5], [6, 7]]

res=np.dot(p,q)
res

array([[16, 19],
       [26, 31]])

In [167]:
p

[[1, 2], [2, 3]]

In [168]:
arr

array([[1, 2],
       [2, 3]])

In [171]:
arr=np.array(p)
arr1=np.array(q)

res=np.dot(arr,arr1)
res

array([[16, 19],
       [26, 31]])

In [164]:
ini_array = np.array([[1, 2, 3], [45, 4, 7], [9, 6, 10]])

res=np.linalg.eigvals([[1, 2, 3], [45, 4, 7], [9, 6, 10]])
res

array([-5.69973694,  0.64746042, 20.05227652])

In [162]:
# import numpy
from numpy import linalg as LA

# using np.eigvals() method
gfg = LA.eigvals([[1, 2, 3], [4, 5, 6], [7, 8, 9]])

print(gfg)


[ 1.61168440e+01 -1.11684397e+00 -3.38433605e-16]


In [165]:
# Python program to inverse
# a matrix using numpy

# Import required package
import numpy as np

# Taking a 3 * 3 matrix
A = np.array([[6, 1, 1],
			[4, -2, 5],
			[2, 8, 7]])

# Calculating the inverse of the matrix
print(np.linalg.inv(A))


[[ 0.17647059 -0.00326797 -0.02287582]
 [ 0.05882353 -0.13071895  0.08496732]
 [-0.11764706  0.1503268   0.05228758]]


# Replace NumPy array elements that doesn’t satisfy the given condition

In [175]:
n_arr = np.array([75.42436315, 42.48558583, 60.32924763])
print("Given array:")
print(n_arr)

n_arr[n_arr<50]=1000

Given array:
[75.42436315 42.48558583 60.32924763]


In [176]:
n_arr

array([  75.42436315, 1000.        ,   60.32924763])

In [178]:
a=np.array([[1,2,3,4],[4,8,9,7]])

b=np.where(a<4)

print(a[b])

[1 2 3]


In [181]:
ini_array = np.array([[1.3, 2.5, 3.6, np.nan], 
                      [2.6, 3.3, np.nan, 5.5],
                      [2.1, 3.2, 5.4, 6.5]])

col_mean=np.nanmean(ini_array,axis=1)

inds=np.where(np.isnan(ini_array))

ini_array[inds]=np.take(ini_array,inds[1])

In [182]:
col_mean

array([2.46666667, 3.8       , 4.3       ])

In [184]:
print(inds)

(array([0, 1], dtype=int64), array([3, 2], dtype=int64))
